project_id = "zlwzuoigrrxwfqsgwuaz"

[functions.process-memo]
verify_jwt = false

[functions.elevenlabs-transcribe]
verify_jwt = false

[functions.summarize-folder]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false